### ISSUE TITLE
Change survey questions

### ISSUE THREAD

**Issue by albche** [tranjack288/CSE-112-Project#5]
Change the survey questions to ask for meta details
ex. whats your budget? are you vegetarian? how much time do you have? etc..

**Comment by GonzaloAllenPerez444** [comment]
Specific implementation details: Create a data source of all of the noodles with categories for spice level, budget, etc. from 1-10. Change each question to implement 10 labels from 1-10 for each, and save users current score in local storage. when the user submits, call a function to return the 4 closest matching noodles. Optionally work on having forward and back buttons instead of instantly submitting a user's choice.
